### ISSUE TITLE
Does wurstmesiter/storm-docker use Monit or deamontools to restart crashed processes?

### ISSUE THREAD

**Issue by nessus42** [wurstmeister/storm-docker#13]
Hi. The official documentation for Storm says that the following processes must be run under Monit or deamontools (or another "supervisor" process) so that if they crash they will be automatically restarted:

* Numbus
* Supervisors
* Zookeeper
* Storm UI

It also says that cron must be configured in order to compact Zookeeper's data and transaction logs.

Are these things arranged for by wurstmeister/storm-docker, or is this something that I would have to configure myself?

Thanks.

|>oug

**Comment by wurstmeister** [comment]
yes, storm-docker uses supervisord.

**Comment by nessus42** [comment]
Excellent! Thanks for the answer. Are the logs also deleted after some amount of time?

**Comment by nessus42** [comment]
Oh, and to make this into a real "issue", perhaps the answers to these questions should be in the README file.

The reason I ask these questions rather than just trying out your docker and seeing how it works for me, is that so often I try out something that is publicly available, only to find out that the answer is "no" and the "easy" solution won't work for me. At least not without a lot of work. If you've carefully made everything turn-key, you should advertise that fact!
